### ISSUE TITLE
Problem by parsing from txt

### ISSUE THREAD

**Issue by MTechDE** [prowide/prowide-core#1]
I want to parse some txt SWIFT Messages into my projekt.
First of all i used some of your examples and then i switched to my own generated swift messages.
I noticed a problem by parsing some 1xx, 2xx,5xx and 9xx SWIFT messages.

```
AbstractMT msg = AbstractMT.parse(new File("example_messages/MT509.txt"));		
System.out.println(msg.message()); // No problem			
System.out.println(msg.getMessageType()); // Returns null
```
I attached the files to this issue report.

You can recheck my messages with this website: http://www.paymentcomponents.com/demo/mt/submit

[MT101.txt](https://github.com/prowide/prowide-core/files/631351/MT101.txt)
[MT103.txt](https://github.com/prowide/prowide-core/files/631353/MT103.txt)
[MT104.txt](https://github.com/prowide/prowide-core/files/631352/MT104.txt)
[MT202.txt](https://github.com/prowide/prowide-core/files/631350/MT202.txt)
[MT509.txt](https://github.com/prowide/prowide-core/files/631355/MT509.txt)
[MT905.txt](https://github.com/prowide/prowide-core/files/631354/MT905.txt)

**Comment by zubri** [comment]
Hi,
Your samples are not pure FIN messages but an MT FIN message with an acknowledge message prefix.
Take a look at this other example to handle it with our library:

https://github.com/prowide/prowide-core-examples/blob/master/src/com/prowidesoftware/swift/samples/core/ParseMessageWithAckExample.java
