### ISSUE TITLE
Major issue in parse field values algorithm

### ISSUE THREAD

**Issue by Ryniu3001** [prowide/prowide-core#100]
There is a bug in parse field values algorithm. For e.g. format of field 48 is **3n[/35x]**, so if we set a value like '12/AFTER B/L DATE WITHIN L/C VALIDITY', then component 1 should be equals '12' and component 2 should be equals 'AFTER B/L DATE WITHIN L/C VALIDITY', but it isn't. The value of component 2 is 'AFTER B'.
Library cuts out all after second slash character. Slashes are allowed in x character set, so in this case it should't be perceived like component separator.

**Comment by sman-81** [comment]
Thanks for reporting this. We'll check whether there is possibly an issue with how parsing is done in `Field48`.

**Comment by Ryniu3001** [comment]
Sorry it's my bad. I was using old version of the library. I the latest version problem doesn't occurs.
