### ISSUE TITLE
Invalid ConstraintValidator annotation on CurrencyValidator

### ISSUE THREAD

**Issue by stevejuma** [prowide/prowide-core#103]
The definition of `CurrencyValidator` https://github.com/prowide/prowide-core/blob/master/src/main/java/com/prowidesoftware/swift/constraints/CurrencyValidator.java#L30 is currently defined with the annotation for `CountryConstraint` need to change this to reference `CurrencyConstraint`.

**Comment by sman-81** [comment]
Thanks for this report! We will have this fixed in the next release.
