### ISSUE TITLE
Parsing MT942 without block 4

### ISSUE THREAD

**Issue by rafael-queiroz-cko** [prowide/prowide-core#109]
Hi guys, when I try to parse a  MT942 file with the following specs for example:

:20:0980000000183630
:25:GB04BARC20000049051544
:28C:9405/2
:34F:EUR0,
:13D:2204081400+0100
:61:2204080408C10,NTRFMIGUEL KOBEISSI //PCTA00LV2098
:86:/SVCL/SEPA/EREF/NOTPROVIDED /REMI/2500COINSLIVU              GIRO
PAY0014403848SL1PJWTSV2 /ORDP//NAME/MIGUEL KOBEISSI Max-Slevogt-S
tr. 4 67434  Neustadt DE/AC/DE84546512400004972188/ORDB//BIC/MALA
DE51DKH/TRN/MALADE51DKH-I1309800573810l7
:61:2204080408C2,9NTRFSayed Mustafa Sa//PCTA00M2Q098
/OCMT/EUR52557992,48/
:86:/SVCL/SEPA/EREF/NOTPROVIDED /REMI/650COINSLIVU               GIRO
PAY0014403848SL1Q8VY2M4 /ORDP//NAME/Sayed Mustafa Sadat Altlaende
r Str. 51 21614 Buxtehude DE/AC/DE97120965970007734255/ORDB//BIC/
GENODEF1S10/TRN/2022040851849868903200000010000001
:61:2204080408C706,NTRFRamona Birgit Mo//PCTA00L52098
/OCMT/EUR52557992,48/
:86:/SVCL/SEPA/EREF/NOTPROVIDED /REMI/ORDER 1930261              GIRO
PAY0014404077SL1Q7JT004 /ORDP//NAME/Ramona Birgit Mordhorst Berli
ner Ring 5a 24610 Trappenkamp DE/AC/DE09212900160078419811/ORDB//
BIC/GENODEF1NMS/TRN/2022040834555383090200000010000001
:61:2204080408C290,NTRFSUSANNE BAUR Ulm//PCTA00LPK098
/OCMT/EUR52557992,48/
:86:/SVCL/SEPA/EREF/NOTPROVIDED /REMI/ORDER 1929873              GIRO
PAY0014404077SL1P7R7Q71 /ORDP//NAME/SUSANNE BAUR Ulmer Str. 89/2 
88471  Laupheim DE/AC/DE10654500700008481906/ORDB//BIC/SBCRDE66/T
RN/SBCRDE66XXX-D0B09766615841k2
:61:2204080408C5,5NTRFALI AMMOURI Kobl//PCTA00L6F098
/OCMT/EUR52557992,48/
:86:/SVCL/SEPA/EREF/NOTPROVIDED /REMI/1250COINSLIVU              GIRO
PAY0014403848SL1PJSN2B2 /ORDP//NAME/ALI AMMOURI Koblenzer Str. 21
0 56073  Koblenz DE/AC/DE79570501200104558069/ORDB//BIC/MALADE51K
OB/TRN/MALADE51KOB-I0D09800372820f6
:90C:5EUR1014,4

It always throws me an error.. if I add the block 4 manually it works.. is there a way to do this in a programmatically way?

**Comment by zubri** [comment]
If your requirement is to only parse block 4 (text block) without the complete message headers and optional trailer. then you could use the method:

/**
     * Parses a string containing the text block of an MT message
     *
     * @param s block content starting with "{4:\r\n" and ending with "\r\n-}"
     * @return content parsed into a block 4 or an empty block 4 if string cannot be parsed
     * @since 7.8.4
     */
    static public SwiftBlock4 parseBlock4(String s)

In the SwiftParser class.
Notice you still have to wrap your input string with the block boundary
