### ISSUE TITLE
getting field label for tag component

### ISSUE THREAD

**Issue by fabiohecht** [prowide/prowide-core#11]
Hi!

Say I have a tag e.g. ":20C::SEME//B0QT080624-00242" and would like to get its localized label for the qualifier component (in this case "Sender's Message Reference").

What would be the best way to do this programmatically?

I tried appending the qualifier to the field name, that is  `Field.getLabel("20c_SEME", "515", "A", Locale.US)` with no success. I guess it's because Field.getNumber() truncates the "_SEME" part. If I change the first parameter to "20a_SEME" it works, but my field in this case is 20c.

Thanks for any help.

Fabio

**Comment by zubri** [comment]
Letter options ar upper case, in your example the correct field name is "20C", no "20c". 
The lower case 'a' is the wildcard used by SWIFT to represent any letter option.

In the resource bundle, we use 'a' for a field when the label is shared between all letter options. That's the reason why it will work with "20a", just by chance.

You should be using something like 
`Field.getLabel(field.getName() + "_" + field.getQualifier(), "515", "A", Locale.US)`


PD: the expanded printout feature in the Prowide Integrator SDK produces human-friendly SWIFT data in TXT, HTML and XML formats out-of-the-box.
https://github.com/prowide/prowide-integrator-examples/blob/master/src/com/prowidesoftware/swift/samples/integrator/ExpandedPrintoutExample.java
If you are interested you can ask for an SDK trial.
