### ISSUE TITLE
Empty tag removed when parsing

### ISSUE THREAD

**Issue by bora-fsd** [prowide/prowide-core#117]
Wondering if this is the intended behavior, I have a sample message:

```
{1:F01ABCDABCDXXXX}{2:I202ABCDABCDXXXXN}{3:{108:TR2021101995111}}{4:
:20:2021101995111
:21:ABCDAB1111CCCCCC
:32A:111111ABC11000000,
:52A:ABCDABABXXX
:57A:ABCDABCDXXX
:58A:/1111-0001
ABCDABABXXX
-}{5:}
```

after parsing this message, the last block (5) does not appear in the message. Is there a way to have block 5 parsed, even if it's empty?

**Comment by ptorres-prowide** [comment]
Hello Bora.
I've run this test that asserts that the block 5 is being parsed to an empty object (not a null one).
Are you expecting to get anything different to this result?
Regards
Pablo

**@Test
public void test() throws IOException {
    String messageToParse = "{1:F01ABCDABCDXXXX}{2:I202ABCDABCDXXXXN}{3:{108:TR2021101995111}}{4:\n" +
            ":20:2021101995111\n" +
            ":21:ABCDAB1111CCCCCC\n" +
            ":32A:111111ABC11000000,\n" +
            ":52A:ABCDABABXXX\n" +
            ":57A:ABCDABCDXXX\n" +
            ":58A:/1111-0001\n" +
            "ABCDABABXXX\n" +
            "-}{5:}";

    SwiftMessage swiftMessage = new SwiftParser(new StringReader(messageToParse)).message();
    assertNotNull(swiftMessage.getBlock1());
    assertNotNull(swiftMessage.getBlock2());
    assertNotNull(swiftMessage.getBlock3());
    assertNotNull(swiftMessage.getBlock4());
    assertNotNull(swiftMessage.getBlock5());
}**

**Comment by bora-fsd** [comment]
Thanks for your response. I found the root cause of the issue. If you try to get the message string back, you'll notice that Block 5 is not there anymore. This is because `ignoreEmptyBlocks` in `SwiftWriter` is by default set to true and cannot be changed by the consumer.
I have a workaround by using a custom `SwiftWriter` and I'm passing `ignoreEmptyBlocks: false`
