### ISSUE TITLE
MT566 - USECU / FIA is not repetitive

### ISSUE THREAD

**Issue by sbublava** [prowide/prowide-core#119]
According to https://www2.swift.com/knowledgecentre/publications/us5mc_20220722/1.0?topic=mt566-format-spec.htm USECU / FIA is not repetitive, but com.prowidesoftware.swift.model.mt.mt5xx.MT566 has getSequenceB1List() instead of getSequenceB1().

com.prowidesoftware.swift.model.mt.mt5xx.MT564 handles this case correctly.

**Comment by ptorres-prowide** [comment]
The issue has been fixed. The changes will be available in the next release.
