### ISSUE TITLE
MT535 Extraction : Parent vs Child field values

### ISSUE THREAD

**Issue by ingridgoh** [prowide/prowide-core#122]
Hello team,

I'm currently working on extracting the entirety of MT535 messages and noticed the following behavior:

When extracting the tag SUBSAFE/94, if there isn't any value allocated to it (i.e. missing in the raw MT535 message), the value of the first child tag 94 (e.g. SUBSAFE/FIN/SUBBAL/94) is taken. 

```
SwiftBlock4 b4 = mt.getSwiftMessage().getBlock4();
b4.getSubBlocks("SUBSAFE").forEach(subsafeBlock -> {
  .
  .
  .
  Field subsafe_94_field = subsafeBlock.getFieldByNumber(94);
  .
  .
  .
}
```

Is this the intended behavior of the library? Is there any way to identify that SUBSAFE/94 does not have a value and produce a null object?

Thank you very much!

**Comment by ptorres-prowide** [comment]
Hello Ingrid, could you share the input data that you're using in this case?
Thank you
Regards

**Comment by ingridgoh** [comment]
Hi, 

Please refer to the attached file for the sample
[mt535_troubleshoot.txt](https://github.com/prowide/prowide-core/files/9632195/mt535_troubleshoot.txt)

Thanks!

**Comment by ingridgoh** [comment]
Hi @ptorres-prowide , are there any updates on this ticket? Thanks!
