### ISSUE TITLE
AbstractMT parser  - Field 50F (MT103 ) is not removing the forward slash 

### ISSUE THREAD

**Issue by robvtang** [prowide/prowide-core#124]
:50F:/728394792
1/LARGE COMPANY
3/TW/NZ
:52A:dadkajdsad
:57A://AU032143
dfghsjdfsf
:59F:/78934758594435
1/TEST ACCOUNT WBC
2/SYDNEY
3/AU/SYDNEY

getBlock4().getFieldByName("50F").getComponent(1) - this returns with "/". that is /728394792
But getBlock4().getFieldByName("59F").getComponent(1) - this returns without "/". that is  78934758594435( that is without /). 

So why the parser is not removing the slash incase of 50F of MT103 message.

**Comment by ptorres-prowide** [comment]
Hello, both field format are different, since that, both are parsed with a different logic and that's the cause why you're getting a slash for one and none for the other.

**Comment by zubri** [comment]
Notice you have also a `getAccount()` method to retrieve the content consistently without slashes in both cases
