### ISSUE TITLE
Field 71B in MT590 component narrative

### ISSUE THREAD

**Issue by AntonioFE2021** [prowide/prowide-core#127]
Hello,
Field71B in MT590 Message is structured in this way:
![image](https://user-images.githubusercontent.com/95424570/197573826-281e8fd6-95b8-40b5-84de-db3cf531fd7f.png)

This means that there are six possibile lines.

We are using last version SRU2022-9.3.5, but I can't  populate all six lines because only the first is available ( component narrative)

```
String _71B= "{\"name\":\"71B\",\"narrative\":\"/WITX/CAPITAL GAINS TAX RELATING TO\",\"narrative2\":\"//THE PERIOD 1998-07-01 2022-10-30\",\"narrative3\":\"//REF 009524780232\",\"narrative4\":\"//BANCA DEL TEST\"}";

Field71B tag71B=Field71B.fromJson(_71B);
```
This is the actual value  of tag71B:
_:71B:/WITX/CAPITAL GAINS TAX RELATING TO//THE PERIOD 1998-07-01 2022-10-30//REF 009524780232//BANCA DEL TEST//(REF. ART. 6 DL 461/97)_

but we would obtain this:
_:71B:/WITX/CAPITAL GAINS TAX RELATING TO
//THE PERIOD 1998-07-01 2022-10-30
//REF 009524780232
//BANCA DEL TEST
//(REF. ART. 6 DL 461/97)_

In which way can we obtain this result?

**Comment by ptorres-prowide** [comment]
Hello Antonio, please check the code below.
Regards

```
    public void testField71B() {
        String _71B = "{\"name\":\"71B\",\"narrative\":\"/WITX/CAPITAL GAINS TAX RELATING TO\n" +
                "//THE PERIOD 1998-07-01 2022-10-30\n//REF 009524780232\n//BANCA DEL TEST\n//(REF. ART. 6 DL 461/97)\"}";
        Field71B tag71B = Field71B.fromJson(_71B);
        for (int i = 1; i<=tag71B.getLines().size(); i++) {
            System.out.println("Line " + i + " contains: " + tag71B.getLine(i));
        }
        assert(tag71B.getLines().size()==5);
    }
```

**Comment by AntonioFE2021** [comment]
Hi Ptorres,
we would like to obtain this result:

_:71B:/WITX/CAPITAL GAINS TAX RELATING TO
//THE PERIOD 1998-07-01 2022-10-30
//REF 009524780232
//BANCA DEL TEST_

But your code generates only one row  containg all four values.


![image](https://user-images.githubusercontent.com/95424570/199775417-0a644258-c95e-4cac-abe8-ae11594decd8.png)

How can I obtain for different lines as in the example above?

In class Field71B.class there were different components for generated lines, but now they are deprecated :

![image](https://user-images.githubusercontent.com/95424570/199777170-67f88c03-f62d-4f8d-9fa2-3aaa5eef90a5.png)

We expected this tag to work in a similar way as Field70E:

![image](https://user-images.githubusercontent.com/95424570/199778036-24595cc5-ae4d-436b-bff0-07efc1d0f0f5.png)


Field71B in MT590 Message is structured in this way, 

![image](https://user-images.githubusercontent.com/95424570/199778580-c7172046-0fb0-4321-9685-dd0813617aaa.png)

Six rows composed by  max 35 chars each.
But there is no way to generate line from 2 to 6.

thanks for your kind reply
Regards,

**Comment by zubri** [comment]
We have enhanced the JSON conversion for NarrativeContainer fields such as 71B in release 9.3.8

Some details at: https://dev.prowidesoftware.com/SRU2022/open-source/core/mt-json/
