### ISSUE TITLE
 Field 71B in MT590 component narrative

### ISSUE THREAD

**Issue by AntonioFE2021** [prowide/prowide-core#132]
Hi,
I reopen this issue because  
we would like to obtain this result:

_:71B:/WITX/CAPITAL GAINS TAX RELATING TO
//THE PERIOD 1998-07-01 2022-10-30
//REF 009524780232
//BANCA DEL TEST_

But your code generates only one row  containg all four values.

![image](https://user-images.githubusercontent.com/95424570/199775417-0a644258-c95e-4cac-abe8-ae11594decd8.png)

How can I obtain for different lines as in the example above?

In class Field71B.class there were different components for generated lines, but now they are deprecated :

![image](https://user-images.githubusercontent.com/95424570/199777170-67f88c03-f62d-4f8d-9fa2-3aaa5eef90a5.png)

We expected this tag to work in a similar way as Field70E:

![image](https://user-images.githubusercontent.com/95424570/199778036-24595cc5-ae4d-436b-bff0-07efc1d0f0f5.png)

Field71B in MT590 Message is structured in this way, 

![image](https://user-images.githubusercontent.com/95424570/199778580-c7172046-0fb0-4321-9685-dd0813617aaa.png)

Six rows composed by  max 35 chars each.
But there is no way to generate line from 2 to 6.

thanks for your kind reply
Regards,

_Originally posted by @AntonioFE2021 in https://github.com/prowide/prowide-core/issues/127#issuecomment-1302372116_

**Comment by zubri** [comment]
We have enhanced the JSON conversion for NarrativeContainer fields such as 71B in release 9.3.8

Some details at: https://dev.prowidesoftware.com/SRU2022/open-source/core/mt-json/
