### ISSUE TITLE
Update the javax.xml.bind:jaxb-api to Jakarta EE apis (supporting Spring Boot 3 releases)

### ISSUE THREAD

**Issue by mohammedamineboutouil** [prowide/prowide-core#140]
Now that Spring Boot 3 is out, and they migrated to jakarta ee prowide-core is not working properly with spring boot 3
I think we should create an release that is compatible with the recently released Spring Boot 3

**Comment by ratoaq2** [comment]
is there a reason for not migrating to jakarta ee?
