### ISSUE TITLE
MT940 Swift message unable to return double value with decimals

### ISSUE THREAD

**Issue by CharithaRat** [prowide/prowide-core#148]
When SWIFT MT940 conversion it return amount as 32 instead of 0.32 from the library.
 
Example MT940 message:
:61:2212051205C,32NDIV252100549047714//RJHIPSH2233901WI000001215560 for tag 61, 
After the conversion amount is getting as 32. But the actual transaction amount is 0.32

Java Code:
double amount = field61.getComponentAsNumber(Field61.AMOUNT).doubleValue())

So is there any way to return decimal values by using same library.

**Comment by zubri** [comment]
Fixed in release SRU2022-9.3.12
