### ISSUE TITLE
How can i de-duplication transaction from MT940 &MT942

### ISSUE THREAD

**Issue by leven-space** [prowide/prowide-core#16]
Hi
Recently, I use this libarary to query SWIFT data. it's a very excellent library.  Thank you for your contribution.   
However，I found duplication transaction in MT940 &MT942，I don't konw about MT940 &MT942 very well.   so can you help me how can  de-duplication transaction？ which tag I can use？

**Comment by zubri** [comment]
For de-duplication you should just iterate and compare the fields 61 instances. Transaction information is found at fields 61 and the optional 86. This example can give you some hints on how to process this messages.

https://github.com/prowide/prowide-core-examples/blob/master/src/main/java/com/prowidesoftware/swift/samples/core/ParseMT940TransactionsExample.java
