### ISSUE TITLE
Incorrect LT identifier handling (AbstractMT)

### ISSUE THREAD

**Issue by sbublava** [prowide/prowide-core#163]
com.prowidesoftware.swift.model.mt.AbstractMT.create(int, String, String) contains this code:

result.setSender(StringUtils.rightPad(sender, 12, 'X'));
result.setReceiver(StringUtils.rightPad(receiver, 12, 'X'));

This is incorrect - because the LT identifiier comes before the branch code - and will fail for BIC11 where the branch code is not XXX, e.g. ZYAFATW0AAA will be converted to ZYAFATW0AAAX instead of ZYAFATW0XAAA.

As far as I can tell, this code is also redundant, because setSender() and setReceiver() call methods in SwiftBlock1 and SwiftBlock2Input which already perform logical terminal address conversion (via LogicalTerminalAddress).

**Comment by sbublava** [comment]
I would either remove the padding alltogether or only pad to 11 characters (to add missing branch identifiers).

**Comment by zubri** [comment]
I agree. I've just removed the unnecessary padding.

**Comment by zubri** [comment]
Fixed in release SRU2022-9.3.16
