### ISSUE TITLE
MT to JSON conversion?

### ISSUE THREAD

**Issue by hakuseki** [prowide/prowide-core#17]
In the documentation it states that MT-JSON Conversion is **back and forth**.

Is it possible to parse a JSON structure into a MT message with your library?

Tried to find some documentation/examples but failed…

Pls advice

Thx for a great API

M

**Comment by zubri** [comment]
Hi,

We've added toJson and fromJson in all model classes (SwiftMessage, MtSwiftMessage and MTnnn). Although, for the SRU2018 release that will be publicly available in October.

Regards.

**Comment by hakuseki** [comment]
thx
