### ISSUE TITLE
Faulty field 253 in MT020Test

### ISSUE THREAD

**Issue by wim82** [prowide/prowide-core#187]
In the code:
https://github.com/prowide/prowide-core/blob/4217ece88af627680504aeb20171de97c636bffb/src/test/java/com/prowidesoftware/swift/model/mt/mt0xx/MT020Test.java#L35C1-L37C54

I think that letter M should not be there in field 253  {253:050719**M**VNDZBET2AXXX0181000391}
It is also present, I assume a typo, in the official swift docs as seen in https://www2.swift.com/knowledgecentre/publications/ufsm_20230720/2.0?topic=mt020.htm

**Comment by zubri** [comment]
Indeed, a typo in the logical terminal address. Thanks for pointing that out.
