### ISSUE TITLE
maven build issues

### ISSUE THREAD

**Issue by alexeev** [prowide/prowide-core#2]
After quick sanity check of the pom.xml in the version SRU2016-7.8.5 I found the following issues:

### 1\) The commons-lang dependency is in the runtime scope

```xml
<dependency>
    <groupId>commons-lang</groupId>
    <artifactId>commons-lang</artifactId>
    <version>2.6</version>
    <scope>runtime</scope>
</dependency>
```

As the result, "mvn clean install" build fails with 100 compilation errors
`error: package org.apache.commons.lang does not exist`

Recommendation: put "commons-lang" into compile scope.

### 2\) The Rhino JS dependency is unused
```xml
<dependency>
  <groupId>rhino</groupId>
  <artifactId>js</artifactId>
  <version>1.7R2</version>
  <scope>runtime</scope>
</dependency>
```

it seems to be superfluous. After searching in source code I haven't found not a single case of usage of this library.

Recommendation: remove the dependency.

### 3\) The module version in the git master branch is without SNAPSHOT suffix

Currently, the pom file in the master branch contains stable version "<version>SRU2016-7.8.5</version>". However, in the development branch one should always setup a SNAPSHOT version of the _future release target_. Please refer the official Maven user guide for details [1].

Recommendations:

* in the master branch, setup a SNAPSHOT version of the next release target, e.g. "SRU2016-7.8.6-SNAPSHOT"
* during the release process, make a git tag for stable version
* use Maven Release plugin in order to automate the release procedure

[1] https://maven.apache.org/guides/getting-started/index.html#What_is_a_SNAPSHOT_version

**Comment by zubri** [comment]
Thanks for the feedback. We'll fix it for the next release.

**Comment by zubri** [comment]
1) and 2) are fixed.

As for 3) notice this public repository is not used for development and SNAPSHOT releases. Conversely, it exposes the source code for stable public releases. 
We update this repo just twice per per year. A mid term update for the current SRU version on May (like current SRU2016_7.8.9), and the update to the new SRU version on October (will be SRU2017_7.9.0). 
We use SNAPSHOT and intermediate releases in our private development repository.
Anyway, thanks for the recommendation. Your feedback is welcome.
