### ISSUE TITLE
SwiftMessage to Text Conversion

### ISSUE THREAD

**Issue by andregasser** [prowide/prowide-core#20]
Hi!

While upgrading from 7.5 to 7.10.3, I've noticed a difference in generation of line breaks, when converting the SwiftMessage to a text representation. It seems as if \n has been replaced by \r\n. 
Can you confirm this? I've checked the release logs but did not find anything clearly related to this. 

I use the ConversionService.getFIN(SwiftMessage) method to convert the SwiftMessage into a textual representation. Is that the recommended approach?

Thanks for any help.

Best regards,
André

**Comment by zubri** [comment]
Hi, 

"ConversionService.getFIN(SwiftMessage)" is the recommended approach when working with the backbone model SwiftMessage. In the MtSwiftMessage or MTnnn model classes you can just call "message()"

As for the the \r\n that's is the correct EOLS expected by SWIFT for the raw FIN format. Regardless of the line breaks you set, the serializer will ensure all line breacks are CRLF in the output String.
According to the changelog, we have added that back in version 7.0 (August 2013).

Regards
