### ISSUE TITLE
Field64 without Field86

### ISSUE THREAD

**Issue by cottiar** [prowide/prowide-core#210]
In an MT940, when field 86, that follows field 64, is absent (due to tis occurrence being optional), value returned for field 64 appears to be incorrect in that it contains a trailing brace (curly bracket):

![image](https://github.com/user-attachments/assets/b50ca514-3c1a-486d-802c-b2ea3bbd3b72)

Output of ```_mt940_1_.getField64().toString()```:

<code>com.prowidesoftware.swift.model.field.Field64@6c0d7c83[components=[C, 241014, CAD, <b>12345,80}</b>],labelMap=<null>]</code>

Could this be a bug? Please advise. TIA.

**Comment by ptorres-prowide** [comment]
Hello cottiar, we've tried to reproduce the issue, but we weren't able to do it.
Check the Junit below:

    @Test
    public void test() {
        String mt = "{1:F01FOOZBEBBD36A6294534377}{2:I940PECSBEBBXXXXN}{3:{108:YSGU59045E078XXX}}{4:\n"
                + ":20:291455021421000\n"
                + ":25:210008148355ARS\n"
                + ":28C:00006/00001\n"
                + ":60F:C241014CAD23450,77\n"
                + ":62F:C241014CAD23456,88\n"
                + ":64:C241014CAD34567,99\n"
                + "-}";

        MT940 mt940 = MT940.parse(mt);

        System.out.println("RESULT: " + mt940.getField64().toString());
    }
    
RESULT: com.prowidesoftware.swift.model.field.Field64@10b4e7f8[components=[C, 241014, CAD, 34567,99],labelMap=<null>]
    
Could you provide some more info about how do you get to the reported case?

Regards

Pablo

**Comment by cottiar** [comment]
Hello Pablo, I was gathering information to add to this case and noticed that I made an error in the agent that seemingly contributed to the problem. I apologize for the false alarm. 

Details: Our agent processes messages that aren't fully complaint to the schema. In other words, we are dealing with the following variation:

```
String mt2 = ":20:291455021421000\n"
           + ":25:210008148355ARS\n"
           + ":28C:00006/00001\n"
           + ":60F:C241014CAD23450,77\n"
           + ":62F:C241014CAD23456,88\n"
           + ":64:C241014CAD34567,99\n";
```

We therefore treat this document with a not-so-neat function that looks like this:

```
private String reTreat(String inDoc) {
		inDoc = inDoc.replace("{5:}", "");
		inDoc = inDoc.replace("-}{1:", "-}${1:");
		inDoc = inDoc.replace("-}\r\n{1:", "-}${1:");
		if (!inDoc.startsWith("{")) {
			inDoc = "{1:F01                      }{2:O940                                           }{3:{108:           /0000}}{4:\r\n"
					+ inDoc.replace("-\r\n:20:",
							"-}${1:F01                      }{2:O940                                           }{3:{108:           /0000}}{4:\r\n:20:")
					+ "-}"; 
// the error was spotted here. The text which is now "-}" earlier was "}" causing the prowide parser to report an extra braces. 
		}
		return inDoc;
	}
```

Thank you for reverting. Much appreciated.
