### ISSUE TITLE
MT300 - multiple E1 sequences

### ISSUE THREAD

**Issue by agabeskiria** [prowide/prowide-core#22]
Hi, in the class com.prowidesoftware.swift.model.mt.mt3xx.MT300, there's the method getSequenceE1, which returns single E1 sequence. But as I checked the protocol, there can be more than one E1 sequences:
http://www.iotafinance.com/en/SWIFT-ISO15022-Message-type-MT300.html
Sequence E1 - Reporting Parties  [ optional, **repetitive** ].
Is than an issue or did I misunderstand something?
Thanks

**Comment by zubri** [comment]
Hi, it is a bug in the generated sequence getter code, it should return a List.

**Comment by zubri** [comment]
Fixed. Patch will be including in the upcoming LTS release in May
