### ISSUE TITLE
MT file in DOS PPC format not alligned to 512 sector size when message greater then 512 characters and not already multiple of 512 sector size

### ISSUE THREAD

**Issue by safet-habibija** [prowide/prowide-core#25]
Method 

`com.prowidesoftware.swift.io.PPCWriter.write(final String msg, final Writer writer) `
[PPCWriter.java](https://github.com/prowide/prowide-core/blob/develop/src/main/java/com/prowidesoftware/swift/io/PPCWriter.java)

calculates message padding incorrectly. 

Instead of 

`int pad = length > 512? length % 512 : 512 - length;`

it should be

`int pad = (512 - (length % 512)) % 512;`

Explanation:

In case when the message is smaller than 512 characters, padding is calculated correctly.
In case when the message is already multiple of 512 sector size, padding is calculated correctly too (0).
But, when the message exceeds 512 characters and is not multiple of 512, the padding is calculated as the DIV of message size and sector size which is wrong because it implies that the message is padded by the number of characters which message extends over predefined sector size and not by the number of characters required to extend message until the boundaries of partially occupied sector.

Example:
Message size 519 characters. Existing solution calculates padding as 519 % 512 which is 7. Following, message is padded by 7 EMPTY characters which implies that the message increases to 526 characters which is not multiple of 512, hence incorrect.

Proposed solution:
Calculate padding as difference between predefined sector size (512) and the DIV between actual message size and sector size. By this way, the padding represents the number of characters required to extend message until the boundaries of partially occupied sector.
Of course, this should be done only if message is not already alligned with sector boundaries. 
On other side, padding can be calculated by the same way, regardless if the message is less then 512 characters or greater than 512 characters.

Example:
1. Message size 414 characters. Padding is calculated as 512 - (414 % 512) which is 98.
Following, message is padded by 98 EMPTY characters which implies that the message increases in size to 512 which is multiple of 512, hence correct.
2. Message size 519 characters. Padding is calculated as 512 - (519 % 512) which is 505.
Following, message is padded by 505 EMPTY characters which implies that the message increases in size to 1024 which is multiple of 512, hence correct.

Regards,

**Comment by zubri** [comment]
Thanks for the fix @safet-habibija 
It will be included in the upcoming release in a few days.
