### ISSUE TITLE
MT 700 TAG 49G cannot insert null value

### ISSUE THREAD

**Issue by shaqimon** [prowide/prowide-core#26]
Hi, has anyone had this problem? Tried to insert null/empty string into tag49G as below

`        Field49G field49G = new Field49G();
        values = new ArrayList<>();
        narrative = f.getTag49G() != null ? f.getTag49G().split("\n") : null;
        if(narrative != null){
            values.addAll(Arrays.asList(narrative)):
        }
        if(values.size() != 0){
            field49G.setNarrative(values.toString());
        } else {
            field49G.setNarrative("");
        }
        fieldList.add(field49G);`

and it returned NoSuchMethodError. What is happening?

Mind you i used the above code for Tag49H and it allows nulls. Both 49G and 49H values are null, but only 49H works.

**Comment by zubri** [comment]
Fields 49G and 49H share the same implementation so you should get the same result. 

Please review the code snippet in your issue because it appears to be missing something. Also the stack trace for the NoSuchMethodError could help

**Comment by marioestradarosa** [comment]
Field49G.java needs to implement MultiLineField  right?

**Comment by zubri** [comment]
Indeed. It is also missing in 45D, 49M and 49N. I'll commit a fix asap.

**Comment by zubri** [comment]
It is fixed. You can create the library from the latest source code with ./gradlew build
