### ISSUE TITLE
Problem with IBAN / BBAN Validation

### ISSUE THREAD

**Issue by Hawk-360** [prowide/prowide-core#28]
Hi,

A couple of days ago we encountered a weird issue where some IBAN/ BBAN are returned valid but other failed even though they were valid.
For example IBAN SC52BAHL01031234567890123456USD is a valid IBAN for Seychelles listed as sample on [https://www.iban.com/structure] 

but when following is executed -
```
    IBAN iban = new IBAN("SC52BAHL01031234567890123456USD");
    iban.isValid();

it returns false.
```

during a quick debugging it looked like we are expecting the last char to be number in IbanValidationUtils.java
This issue is reproducible in both version we checked -
1) pw-swift-core-SRU2018-7.10.3 
2) pw-swift-core-SRU2019-8.0.1 

Please assist with this,
Thanks,

**Comment by zubri** [comment]
Fixed
