### ISSUE TITLE
Amount subfield of tag 61 in MT942 converted to int value

### ISSUE THREAD

**Issue by ant-1** [prowide/prowide-core#3]
I'm not an swift message expert but I think that the amount subfield (component 5) of Tag 61 in MT942 message should have not been parse to Integer variable as it removes all the decimal values

```java
public Field61 setComponent5(Number var1) {  
    if(var1 != null) {
        this.setComponent(5, "" + var1.intValue());
    }
    return this;
}
```
If I take a look at the tag 32A of the MT900 message , the static method SwiftFormatUtils.getNumber is used to format the amount as required.
I think the same format could be applied for the tag 61 of MT942 message
```java
public Field32A setComponent3(Number var1) {
        this.setComponent(3, SwiftFormatUtils.getNumber(var1));
        return this;
}

**Comment by zubri** [comment]
You are right about that setter from Number. We'll fix it for next release. You can work around the issue with:

`setComponent5(SwiftFormatUtils.getNumber(amount))`

Or using the setter from String.

Notice the parser works just fine. Just in case you need to parse a received statement, you may find interesting the example: https://github.com/prowide/prowide-core-examples/blob/master/src/com/prowidesoftware/swift/samples/core/ParseMT940FromStringExample.java

**Comment by ant-1** [comment]
Great, thanks for the WA !
