### ISSUE TITLE
Reading MT940 Rabobank results in NULL without errors

### ISSUE THREAD

**Issue by stefanhendriks** [prowide/prowide-core#31]
I am researching which MT940 parser is able to import dutch bank MT940 formats. So far I found that , even though all banks claim to export in MT940, the results vary and thus the import results vary greatly as well.

Prowide-core seems to be the most comprehensive suite, but so far no luck importing RaboBank MT940 exports.

I have taken a look at the example java files, and came up with this to try to import an MT940 example file I have:

```
String content = readFileFromResources("MT940_A_20190220_104935.swi", Mt940Parser.class);
		
// try SwiftParser
SwiftParser swiftParser = new SwiftParser(content);		
swiftParser.message();
List<String> errors = swiftParser.getErrors();
System.out.println(errors);

SwiftMessage sm = SwiftMessage.parse(content);
		
if (sm.isServiceMessage()) {
	sm = SwiftMessage.parse(sm.getUnparsedTexts().getAsFINString());
}
		
System.out.println(sm.getTypeInt()); // prints -1
System.out.println(sm.getServiceTypeIdentifier()); // prints null
System.out.println(sm.getBlockCount()); // prints 0
System.out.println(sm.getCategory()); // prints null
		
// Fails:
Assert.assertTrue(sm.isType(940));
```

The `content` variable is a String of the file contents. I tried several ways (including using `InputStream` etc and directly calling `Mt940.parse()`).

Executing the above code results in:
- no errors being printed 
- sm is of no type (ie, the assertion failed, but)

Raw output:
```
Reading file from resources : MT940_A_20190220_104935.swi
[]
sep 28, 2020 3:26:34 PM com.prowidesoftware.swift.model.SwiftMessage getTypeInt
WARNING: Error converting type to int null
-1
null
0
null
sep 28, 2020 3:26:34 PM com.prowidesoftware.swift.model.SwiftMessage getTypeInt
WARNING: Error converting type to int null
```

Here is the very start of the MT940 being imported, including first `:61:` tag.

```
:940:
:20:940S190212
:25:NL27RABO1234567890 EUR
:28C:19030
:60F:C190211EUR000000246311,62
:61:190211C000000000157,30N541NONREF
NL27RABO1234567890
:86:/TRCD/541/ORDP//NAME/Mr Foo/REMI/201134296/ISDT/2019-02-11
:61:190212C000000000272,25N541NONREF
```

I don't see any starts or ending of blocks. Not sure why, but I get the impression the Rabobank does not export it as such. [Their MT940 description tells me that](https://www.rabobank.nl/images/Formaatbeschrijving-MT940S_29959243.pdf)

On the other hand, I can't imagine this is the first time someone tried to import a Rabobank MT940 file, so I guess I do something wrong?

NOTE: I also tried the exact same test code with a MT940 from Knab (other bank), and it works fine.

**Comment by stefanhendriks** [comment]
FYI: the Rabobank PDF says themselves:

```
De door Rabo Internetbankieren (Professional), Rabo Direct Connect en SWIFT FileAct geleverde
MT940 Structured is niet geheel SWIFT-conform. Zo begint het bericht bijvoorbeeld met de
aanduiding :940: en is de berichtomvang niet beperkt tot de toegestane berichtomvang v an
SWIFT. Het afschrift is leeg indien er geen boekingen beschikbaar zijn voor de opgegeven
boekdatum. Het afschrift wordt altijd afgesloten met veld 62F, 64 of 65. 

```

In english, the first sentence, means roughly:
`The MT940 Structured delivered by Rabo Internetbankieren (Professional), Rabo Direct Connect and SWIFT FileAct are 
not entirely SWIFT-conform`

Even still... am I the first to try to import this file using Prowide?

**Comment by zubri** [comment]
Hi Stefan, 

The root cause is your file does not appears to be a complete FIN message but just an extract of the Text block.

A workaround would be parsing just the block 4 (the content you actually have, and building the rest of the message your self.
Something like:

> MT940 mt = new MT940("SENDNLXXXXX", "RECVNLXXXXX");
> String textBlock = "{4:" + StirngUtils.substringAfter(content, ":940:") +  "\n-}";
> SwiftBlock4 block4 = SwiftParser.parseBLock4(textBlock);
> mt.getSwiftMessage().setBlock4(block4);

Notice the `:940:` is custom from that Rabobank format, not part of the block. You could use it as message identifier to know which MT you have to create. Also to remark, your format does not have the sender and receiver. I'm setting fixed values in the above MT constructor.

Somehow to the block 4 parse you have to provide a valid FIN text block such as:

> {4: [LF]
> :20:940S190212 [LF]
> :25:NL27RABO1234567890 EUR [LF]
> :28C:19030 [LF]
> :60F:C190211EUR000000246311,62 [LF]
> :61:190211C000000000157,30N541NONREF [LF]
> NL27RABO1234567890 [LF]
> :86:/TRCD/541/ORDP//NAME/Mr Foo/REMI/201134296/ISDT/2019-02-11 [LF]
> :61:190212C000000000272,25N541NONREF [LF]
> -}

**Comment by frankmichel** [comment]
Heel veel nieuwe .mt940 bestanden:

[mt940bestanden.zip](https://github.com/prowide/prowide-core/files/5446088/mt940bestanden.zip)
