### ISSUE TITLE
mt942.getField60F() not implemented

### ISSUE THREAD

**Issue by gmaczuga** [prowide/prowide-core#32]
mt942.getField60F().getCurrency(), is not implemented while according to 
http://www.iotafinance.com/en/SWIFT-ISO15022-Message-type-MT942.html
this field is optional and can be present (same as for MT940 and MT950)

**Comment by zubri** [comment]
Hi, 

The spec you refer is not accurate or at least it does not match the SWIFT MT specification
<img width="645" alt="Screen Shot 2020-09-30 at 14 04 33" src="https://user-images.githubusercontent.com/3846086/94716934-fdb36d80-0325-11eb-9dde-0daa053b12e1.png">

Anyway, if you need to process such messages you can still use the SwiftMessage model and parser. It will parse any combination of fields in MT. You won't have the getters in an MT942 class, however that class is just a facade for convenience. Those getter implementation use the underlying SwiftTagListBLock which is a collection of Tag objects. Then you can convert any Tag object to its corresponding Field instance and get the internal components such as the currency you refer to.

https://www.prowidesoftware.com/resources/SWIFT-model

**Comment by gmaczuga** [comment]
@zubri thanks a lot for explanation!
