### ISSUE TITLE
MtSwiftMessage.parse shows incorrect month on all date fields (lastModified, creationDate, valueDate)

### ISSUE THREAD

**Issue by icrodolpho** [prowide/prowide-core#35]
When a swift message is parsed all date fields shows an incorrect month value when I execute .toJson().
LastModified and CreationDate should have today's date (Oct-05), but it contains Sep-05 instead.
The same happens to ValueDate.

**Comment by zubri** [comment]
Hi,

Notice month field in Java Calendar are zero based:

https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html#OCTOBER
October is int 9 in the model.

The toJson serialises the fields in the Calendar as is. And the fromJson parses that consistently. So if you serialise a message and deserialise it back, the original Calendar records is preserved.

It could be misleading when you just see the data in the JSON, but is consistent with the legacy Calendar API.
