### ISSUE TITLE
Generic MT class to modify message contents

### ISSUE THREAD

**Issue by saravanakite** [prowide/prowide-core#36]
I want to update some basic tags like tag 20, 21, 22A, 72 in the different MT message say MT300, MT304, MT398. Instead of parsing the message using specific MT class and modifying using SwiftBlock4 is there any generic way to do this? Only these line of code is different for each message assume I already know the message type. 

MT300 mt300 = MT300.parse(incoming_message);
MT304 mt304 = MT304.parse(incoming_message);
MT398 mt398 = MT398.parse(incoming_message);

**Comment by zubri** [comment]
The MTnnn are facades. The underlying model is the generic SwiftMessage where the block 4 is a list of generic Tag objects.

You can parse directly with SwiftMessage.parse(fin) the from there you can access the different Tag objects and change its values as needed.

https://www.prowidesoftware.com/resources/SWIFT-MT-modification
