### ISSUE TITLE
Convert from one message type to another

### ISSUE THREAD

**Issue by saravanakite** [prowide/prowide-core#37]
Is there a way to convert message from one message type to another? Eg MT 300 to MT 396

**Comment by zubri** [comment]
No like that with specific API but you can use the SwiftMessage model for that. altering the source MT to convert it to something else or copying the tags you want to propagate to another MT instance.

You could also convert the message into XML, use XML transformation API to manipulate the content, and parse the final XML back into an SwiftMessage instance. You have back and forth conversion to a proprietary XML structure in the library: https://www.prowidesoftware.com/resources/SWIFT-XML

Depending on the use case, you might be interested on this as well: https://www.prowidesoftware.com/products/integrator/my-format
It is intended for conversion into proprietary formats but you can also use it to convert one MT into another, by defining mapping rules.
