### ISSUE TITLE
MT564 Issue with sequence getFieldsByName() 

### ISSUE THREAD

**Issue by CBhavsar-Fintech** [prowide/prowide-core#41]
Hi- 

We are working on MT564 parsing. we are facing an issue while parsing sequence E (Corporate action option) and E2(Cash movement).  when we call getFieldsByName() with 92 field (A,B,F,H,J,K,R,M). 

Issue is:  If this field(92) is present in cash movement sequence only
then it is being parsed in sequence E and also in sequence E2 both. 
actually it should be parsed in E2 sequence only when it is present E2 sequence of MT564.

Please find below attached MT564 msg which we are trying to parse but :92J::GRSS//INCO/USD0,1234567/ACTU 
is parsed in both sequence E and sequence E2.

We are using release- SRU2018-7.10.4

[MT564.txt](https://github.com/prowide/prowide-core/files/5763469/MT564.txt)

**Comment by JVaghela-Fintech** [comment]
@zubri  please let us know once the release published to git.

**Comment by zubri** [comment]
Hi,

The PR is just a test case with API usage examples:
https://github.com/prowide/prowide-core/blob/develop/src/test/java/com/prowidesoftware/swift/issues/Issue41.java

Notice the sequence API returns always list of fields, including all elements of the inner sequences. If you retrieve sequence E, it will contain all fields that are exclusive for E but also all fields in the inner sequences E1, E2, etc... The implementation is just a message split by sequence boundary fields, not a nested structure.

Thus when you retrieve a field by number or name from sequence E, you will also get any instance of the field in the inner sequences. 

To retrieve fields only in the specific parent sequence, example E, you have to first trim the inner sequence elements before; as in the test example.
