### ISSUE TITLE
MT094 - Block4 - parsing issue

### ISSUE THREAD

**Issue by mjp94** [prowide/prowide-core#46]
Hi,

We're working on MT094 system messages. We're facing an issue while parsing block 4 of MT094 messages.

While parsing block4, the parser will only identify tags where the name is of 2 digits and may contain the optional trailing character. tag name pattern = nn[a]

For ex: if tag name is 20C, then the parser will be able to identify the tag, but if the tag name is 136 (which are of 3 digits) if will fail to identify the tags.

Consider following block4 from MT094 message:

{4:
:135:N
:136:S01234
:129:01/01
:130:/31/SWIFT NOTIFICATION
/01/GENERAL
SWIFT HEADQUARTERS
:312:Some message
-}

Parsing Result: ["135":"N\r\n:136:S01234\r\n:129:01/01.......\r\n:312:Some message"]

Here, the parser will identify the first tag of block4 which is 135. It'll be able to identify it as the identification logic for the first tag is different from the subsequent tag of block4.

To identify subsequent tags, the parser will look for tag names in the pattern nn[a] (2 digits with the optional trailing character).

But the tag names of MT094 are of 3 digits due to which the parser is not able to identify subsequent tags.

Reference: [SwiftParser.java](https://github.com/prowide/prowide-core/blob/develop/src/main/java/com/prowidesoftware/swift/io/parser/SwiftParser.java) -> isTagStart()

Note: No issues with the input message format related to CRLF.

Thanks.

**Comment by zubri** [comment]
Hi,

System and service messages such as the MT094 should use a different structure for block 4 where fields are not split by CRLF but structures in inner blocks. For example, this is an MT012:

{1:F01FOOOUSC0AXXX3545000047}{2:I012BAAARUSC0XXXXN}{4:{175:1023}{106:091203BANKBEBBAXXX2222123456}{108:MUR111222333}{102:ABCDUSAAXXXX}{103:TGT}{114:FOO}}

If you structure your fields in inner blocks, as expected for an MT094, then the parser will be able to consume the block 4 properly.

**Comment by mjp94** [comment]
Hi @zubri, thanks for the response. 
I've verified our messages and as you mentioned, the format was wrong for MT094.

Now, we are able to parse it successfully.
Thanks.
