### ISSUE TITLE
Example to remove a tag and it's value from swift message

### ISSUE THREAD

**Issue by saravanakite** [prowide/prowide-core#52]
I have reviewed all examples but there is no example on how to remove a tag and it's value from swift message. Appreciate your help.

**Comment by saravanakite** [comment]
@zubri Please assist

**Comment by zubri** [comment]
Check out this example

https://github.com/prowide/prowide-core-examples/blob/master/src/main/java/com/prowidesoftware/swift/samples/core/MessageModificationRemoveTagExample.java

You can remove by tag name or by index in the tag list.
