### ISSUE TITLE
prowide-integrator-examples validator example

### ISSUE THREAD

**Issue by CBhavsar-Fintech** [prowide/prowide-core#56]
Hi,

We are looking to validate swift messages using validator.

when we try to initialize ValidationEngine, we are getting exception as follows.

Please suggest !!

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/mozilla/javascript/Context] with root cause

Below is the code 
----------------------

ValidationEngine engine = new ValidationEngine();
                engine.initialize();
                String msg = messageRequestModel.getMessageBody();
                List<ValidationProblem> r = engine.validateMtMessage(msg);
                System.out.println(ValidationProblem.printout(r));
                engine.dispose();

-----------------------------------------------------------------

build.gradle 
-----------------------

repositories {
    mavenCentral()
    flatDir {
        dirs 'C:\\libs'
    }
}

dependencies {
    compile("org.springframework.boot:spring-boot-starter-web")
    //compile group: 'com.prowidesoftware', name: 'pw-swift-core', version: 'SRU2020-9.1.2'
    //compile group: 'com.prowidesoftware', name: 'pw-iso20022', version: 'SRU2020-9.1.5'

    implementation name:  'pw-iso20022-SRU2020-9.1.7'
    implementation  name: 'pw-swift-core-SRU2020-9.1.5'

    implementation  name: 'pw-swift-integrator-CBPR-1.2u2'
    implementation  name: 'pw-swift-integrator-data'
    implementation  name: 'pw-swift-integrator-myformat-SRU2020-9.1.11'

    implementation  name: 'pw-swift-integrator-SCORE-1.0.0'
    implementation  name: 'pw-swift-integrator-sdk-SRU2020-9.1.14'
    implementation  name: 'pw-swift-integrator-SEPA-2019v1.0u2'

    implementation  name: 'pw-swift-integrator-SIC-4.6u2'
    implementation  name: 'pw-swift-integrator-translations-SRU2020-9.1.17'
    implementation  name: 'pw-swift-integrator-validation-SRU2020-9.1.16u1'

    compile 'org.springframework.boot:spring-boot-starter-log4j2'
}

**Comment by svdkar** [comment]
Validation is a commercial product. You need a license to use that module.

**Comment by CBhavsar-Fintech** [comment]
Yes, We do have Licence for using it.

**Comment by svdkar** [comment]
> Yes, We do have Licence for using it.

The open a ticket on the JIRA portal.
