### ISSUE TITLE
Field98C - Parses to null value for value length < 8

### ISSUE THREAD

**Issue by vishnupaturi** [prowide/prowide-core#60]
Field98C skips populating the component for the value length < 8. 
98C comprises of 2 components date and time and if the input value given is of length < 8, resulting value in component is null and this causes consuming component get empty vs provided input for further action. 

_**I feel, this should be fixed to add another block of code 
 if (toparse.length() < 8) {
				setComponent2(StringUtils.substring(toparse, 0, toparse.length));
			}**_

public void parse(final String value) {
		init(3);
		setComponent1(SwiftParseUtils.getTokenFirst(value, ":", "//"));
		String toparse = SwiftParseUtils.getTokenSecondLast(value, "//");
		if (toparse != null) {
			if (toparse.length() >= 8) {
				setComponent2(StringUtils.substring(toparse, 0, 8));
			}
			if (toparse.length() > 8) {
				setComponent3(StringUtils.substring(toparse, 8));
			}
		}
	}

**Comment by vishnupaturi** [comment]
Could you please advise on the issue ?

**Comment by ptorres-prowide** [comment]
The issue is already fixed. New logic will be available in the next oficial release (or you can build the code in case you need to). Regards! :)

**Comment by vishnupaturi** [comment]
Thank you for considering the fix. Do you know the release schedule ?

**Comment by zubri** [comment]
SRU2020-9.1.8 has been released, will be available at Maven Central soon. Regards

**Comment by vishnupaturi** [comment]
Great, Much appreciated.
