### ISSUE TITLE
JPMS support

### ISSUE THREAD

**Issue by sman-81** [prowide/prowide-core#62]
It would be nice to have the library support the Java Platform Module System (JPMS).
We would like to use `com.prowidesoftware:pw-swift-core` with Java 17.
A good solution is to provide a multi-release jar.
Please let me know if I can/should contribute.

Thanks!
Markus

**Comment by sman-81** [comment]
Hi Sebastian (@zubri),
just upgraded to version SRU2021-9.2.7 today, and it builds fine using Java 17, and all tests are green.
Have I been seeing ghosts? I will look into it more deeply as I am moving to Java 17 in my project (currently still Java 11).
cheers!
Markus

**Comment by zubri** [comment]
OK, sounds good. We use basic Java packages and minimal dependencies so it would actually be strange id it cannot be run in Java 17. At most you could be missing javax.persistence and javax.xml.bind but that is fixed by adding a couple of dependencies.

**Comment by sman-81** [comment]
Please add the **Automatic-Module-Name** attribute to the jar's manifest.
It will do away with the warning
`Name of automatic module 'pw.swift.core.SRU2021' is unstable, it is derived from the module's file name.`

**Comment by zubri** [comment]
Added com.prowidesoftware.core as automatic module name in the MANIFEST for JPMS support

**Comment by zubri** [comment]
Version 9.2.9 has been release including this fix. The package will be available at Maven Central soon.

**Comment by sman-81** [comment]
Thanks, just upgraded 👍
