### ISSUE TITLE
Message MT537 - Error reading Block B (STAT) 

### ISSUE THREAD

**Issue by AntonioFE2021** [prowide/prowide-core#78]
I have use library prowide  version SRU2021-9.2.8 and i have a problem to read tag into block B (STAT). 
This is a minimal example: 
**File MT537.txt**
_{1:...}{2:O537....}{3:{108:..}}{4:
:16R:GENL
:28E:5/LAST
:20C::SEME//000000000000251C
......
16S:GENL
16R:PENA
:16R:PENACUR
:16R:PENDET
:16R:RELTRAN
:16R:TRAN
:16R:STAT
:25D::IPRC//CPRC
:16R:REAS
:24B::CAND//CANI
:70D::REAS//XXXXX - Failure of the settlement
XXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXX
terparty
:16S:REAS
:16S:STAT
...._
closing tag TRAN, REALTRAN, PENDET,PENACUR,PENA.

**My code:**
AbstractMT mt = AbstractMT.parse(new String("MT537.txt"));
List<SwiftTagListBlock> swfTagList = mt.getSequenceList("B"); // **Sequence B is BLOCK STAT**
/*if i try to get the taglist with  List<SwiftTagListBlock> swfTagList = mt.getSequenceList("B"); i get the ones of the seq "D1a1B1a" instead "*/

Thanks for the support

**Comment by zubri** [comment]
Hi,

The generic mt.getSequenceList(String) will just select sequences based on the fields boundaries 16R/16S with qualifier "STAT". For this particular MT the B delimiter overlaps with C3 delimiter, both use the "STAT". 
So the generic API cannot handle it.

If instead you call the getSequenceBList() in the specific MT537 class, the result will be correct. Since there is a strategy to select the specific STAT subsequences for that MT, avoiding the qualifier overlapping.

That's one of the advantages of using the MTnnn facades.

Regards

**Comment by AntonioFE2021** [comment]
Hi zubri,
I have call getSequenceBList() of the MT537 class, but result not is correts.

![image](https://user-images.githubusercontent.com/95424570/145021098-e627788b-cc1e-491f-b1c3-7978e1dbb320.png)

In this image, there are 5 elements:

- [0] first element is block MT537/STAT, Sequence B.
- **[1]..[4] elements block MT537/PENA/PENACUR/PENDET/RELTRAN/TRAN/STAT, Sequence D1a1B1a**

Can you verify? 

Regards

**Comment by zubri** [comment]
Looks good to me, 0 to 4 appear to be sequence B instances. It's difficult to tell without the actual message sample.

Notice though, when you get a sequence, all its inner content is included. So when you retrieve sequence B (STAT) the tags from inner sequences B1 (REAS) will be included.

If you want just the fields in the retrieved parent sequence without any element from inner sequence you have the API:

SwiftTagListBlock trimmedSequenceB = SwiftMessageUtils.removeInnerSequences(mt.getSequenceBList().get(0));

**Comment by AntonioFE2021** [comment]
This is example messages:
MT537.txt:

_{1:F01XXXXXXXX0AXXX0400996471}{2:O5371305211201XXXXXXXXAXXX14523429742112011305N}{3:{108:xxxxxxxx}}{4:
:16R:GENL
:28E:5/LAST
:13A::STAT//513
:20C::SEME//000000000000251C
:23G:PENA
:98A::STAT//19700130
:22F::SFRE//DAIL
:22F::CODE//DELT
:22H::STST//PENA
:95P::ACOW//XXXXXXXX001
:97A::SAFE//NONREF
:17B::ACTI//Y
:16S:GENL
:16R:STAT
:25D::IPRC//CPRC
:16R:REAS
:24B::CAND//CANI
:70D::REAS//SXAA015 - Failure of the settlement
XXXXXXXX0XXXXXXXX0XXXXXXXX0
XXXXXXXX0XXXXXXXX0XXXXXXX0
XXXXXXXX0XXXXXXXX0XXXXXXXX0
terparty
:16S:REAS
:16S:STAT
:16R:PENA
:69A::STAT//19700101/19700130
:22F::CODE//CURR
:95P::ASDP//XXXXXXXXXXX
:16R:PENACUR
:11A::PECU//EUR
:98A::DACO//19700130
:95P::REPA//XXXXXXXX001
:95P::CASD//XXXXXXXX0XX
:95P::DCSD//XXXXXXXX0XX
:22F::TRCA//CSDP
:16R:PENACOUNT
:95P::REPA//XXXXXXXX0XX
:22F::TRCA//CCPA
:19A::AGNT//EUR1111,11
:16R:PENDET
:20C::PCOM//211130067774271
:20C::PREF//N211130067774271
:22H::PNTP//SEFP
:22H::CALM//SECU
:17B::CMPU//N
:25D::PNST//ACTV
:19A::AMCO//EUR111,
:99A::DAAC//001
:16R:CALDET
:98A::PEDA//19700130
:16R:FIA
:35B:ISIN XXXXXXXX0
:12A::CLAS/REGL/SOVR
:92A::GOMB//0,001
:16S:FIA
:19A::SECU//EUR1,
:16S:CALDET
:16R:RELTRAN
:20C::ACOW//NONREF
:20C::MITI//7001012161218562
:16R:TRAN
:22H::REDE//RECE
:22H::PAYM//APMT
:22F::SETR//REPU
:22F::TRAN//SETT
:22F::BDEV/T2S/IDVP
:98A::SETT//19700129
:98C::ASTS//19700126181652
:98C::MTCH//19700126181652
:98C::SCTS//19700130143000
:97A::SAFE//XXXXXXXXXX001000L10
:95P::ACOW//XXXXXXXX001
:36B::PSTA//FAMT/10000000,
:19A::PSTA//EUR111111,11
**:16R:STAT
:25D::SETT//PENF
:16R:REAS
:24B::PENF//CLAC
:70D::REAS//SXAA015 - example
example example example
example example example
example example example
terparty
:16S:REAS
:16S:STAT
:16S:TRAN
:16S:RELTRAN
:16S:PENDET
:16S:RELTRAN
:16S:PENDET
:16S:PENACOUNT
:16S:PENACUR
:16S:PENA
-}{5:{CHK:0F4F93C68EA5}{TNG:}}_


......
SequenceB is :
_:16R:STAT
:25D::IPRC//CPRC
:16R:REAS
:24B::CAND//CANI
:70D::REAS//SXAA015 - Failure of the settlement
XXXXXXXX0XXXXXXXX0XXXXXXXX0
XXXXXXXX0XXXXXXXX0XXXXXXX0
XXXXXXXX0XXXXXXXX0XXXXXXXX0
terparty
:16S:REAS
:16S:STAT_

My code is : 
MT537 mt537= MT537.parse(new String("MT537.txt"));
mt537.getSequence**B**List(); --> [0] sequenceBList() correct, [1] sequenceBlist() error, becouse contains sequence D1a1B1a. 
This sequence must contain only the first block STAT.

![image](https://user-images.githubusercontent.com/95424570/145054439-f9c5d862-a88a-4a48-abd5-da2a0ec0f94e.png)

Can you testing this message?

Regards

**Comment by zubri** [comment]
Your sequence boundary fields are not balanced. 
The sequence API cannot ensure any valid result if the boundary fields are not ok.

:16R:GENL
:16S:GENL
:16R:STAT
	:16R:REAS
	:16S:REAS
:16S:STAT
:16R:PENA
	:16R:PENACUR
		:16R:PENACOUNT
			:16R:PENDET
				:16R:CALDET
					:16R:FIA
					:16S:FIA
				:16S:CALDET
				:16R:RELTRAN
					:16R:TRAN
						:16R:STAT
							:16R:REAS
							:16S:REAS
						:16S:STAT
					:16S:TRAN
				:16S:RELTRAN
			:16S:PENDET
		 :16S:RELTRAN  ??
		 :16S:PENDET
		:16S:PENACOUNT
	:16S:PENACUR
:16S:PENA

**Comment by AntonioFE2021** [comment]
ok ok..I made a mistake reporting only a section of the message, sorry.

This message is orginal correct message with anonymous values:
_{1:F01XXXXXXX0AXXX0400996471}{2:O5371305211201XXXXXXX0AXXX14523429742112011305N}{3:{108:GCH-xxxxxxxxxxxx}}{4:
:16R:GENL
:28E:5/LAST
:13A::STAT//513
:20C::SEME//000000000000251C
:23G:PENA
:98A::STAT//20211130
:22F::SFRE//DAIL
:22F::CODE//DELT
:22H::STST//PENA
:95P::ACOW//XXXXXXXXX01
:97A::SAFE//NONREF
:17B::ACTI//Y
:16S:GENL
:16R:STAT
:25D::IPRC//CPRC
:16R:REAS
:24B::CAND//CANI
:70D::REAS//SXAA015 - Failure of the settlement
DESCRIPTION 111
DESCRIPTION 112
DESCRIPTION 113
terparty
:16S:REAS
:16S:STAT
:16R:PENA
:69A::STAT//20211101/20211130
:22F::CODE//CURR
:95P::ASDP//XXXXXXXXXXX
:16R:PENACUR
:11A::PECU//EUR
:98A::DACO//20211130
:95P::REPA//XXXXXXXXD01
:95P::CASD//XXXXXXXXXXX
:95P::DCSD//XXXXXXXXXXX
:22F::TRCA//CSDP
:16R:PENACOUNT
:95P::REPA//XXXXXXXXXXX
:22F::TRCA//CCPA
:19A::AGNT//EUR1,04
:16R:PENDET
:20C::PCOM//211130067774271
:20C::PREF//N211130067774271
:22H::PNTP//SEFP
:22H::CALM//SECU
:17B::CMPU//N
:25D::PNST//ACTV
:19A::AMCO//EUR1,
:99A::DAAC//001
:16R:CALDET
:98A::PEDA//20211130
:16R:FIA
:35B:ISIN XX000000
:12A::CLAS/REGL/SOVR
:92A::GOMB//0,001
:16S:FIA
:19A::SECU//EUR11,
:16S:CALDET
:16R:RELTRAN
:20C::ACOW//NONREF
:20C::MITI//2111262161218562
:16R:TRAN
:22H::REDE//RECE
:22H::PAYM//APMT
:22F::SETR//REPU
:22F::TRAN//SETT
:22F::BDEV/T2S/IDVP
:98A::SETT//20211129
:98C::ASTS//20211126181652
:98C::MTCH//20211126181652
:98C::SCTS//20211130143000
:97A::SAFE//XXXXXXXXXXXXXX1000XX0
:95P::ACOW//XXXXXXXXX01
:36B::PSTA//FAMT/50000000,
:19A::PSTA//EUR1111111,
:16R:STAT
:25D::SETT//PENF
:16R:REAS
:24B::PENF//CLAC
:70D::REAS//SXAA015 - Failure of the settlement
DESCRIPTION 101
DESCRIPTION 102
DESCRIPTION 103
:16S:REAS
:16S:STAT
:16S:TRAN
:16S:RELTRAN
:16S:PENDET
:16R:PENDET
:20C::PCOM//211130067807953
:20C::PREF//N211130067807953
:22H::PNTP//SEFP
:22H::CALM//SECU
:17B::CMPU//N
:25D::PNST//ACTV
:19A::AMCO//EUR111,5
:99A::DAAC//001
:16R:CALDET
:98A::PEDA//20211130
:16R:FIA
:35B:ISIN XX00000000
:12A::CLAS/REGL/SOVR
:92A::GOMB//0,001
:16S:FIA
:19A::SECU//EUR111,5
:16S:CALDET
:16R:RELTRAN
:20C::ACOW//NONREF
:20C::MITI//2111242159118671
:16R:TRAN
:22H::REDE//RECE
:22H::PAYM//APMT
:22F::SETR//TRAD
:22F::TRAN//SETT
:22F::BDEV/T2S/IDVP
:98A::SETT//20211125
:98C::ASTS//20211124181453
:98C::MTCH//20211124181453
:98C::SCTS//20211130143000
:97A::SAFE//XXXXXXXXXXXXXX1000X0
:95P::ACOW//XXXXXXXMD01
:36B::PSTA//FAMT/50000000,
:19A::PSTA//EUR111111111,75
:16R:STAT
:25D::SETT//PENF
:16R:REAS
:24B::PENF//CLAC
:70D::REAS//SXAA015 - Failure of the settlement
DESCRIPTION 1
DESCRIPTION 2
DESCRIPTION 3
:16S:REAS
:16S:STAT
:16S:TRAN
:16S:RELTRAN
:16S:PENDET
:16R:PENDET
:20C::PCOM//211130067821332
:20C::PREF//N211130067821332
:22H::PNTP//SEFP
:22H::CALM//SECU
:17B::CMPU//N
:25D::PNST//ACTV
:19A::AMCO//EUR111,
:99A::DAAC//001
:16R:CALDET
:98A::PEDA//20211130
:16R:FIA
:35B:ISIN XX00000000
:12A::CLAS/REGL/SOVR
:92A::GOMB//0,001
:16S:FIA
:19A::SECU//EUR111,
:16S:CALDET
:16R:RELTRAN
:20C::ACOW//NONREF
:20C::MITI//2111242159121848
:16R:TRAN
:22H::REDE//RECE
:22H::PAYM//APMT
:22F::SETR//TRAD
:22F::TRAN//SETT
:22F::BDEV/T2S/IDVP
:98A::SETT//20211125
:98C::ASTS//20211124181533
:98C::MTCH//20211124181533
:98C::SCTS//20211130143000
:97A::SAFE//XXXXXXXXXXD01000L10
:95P::ACOW//XXXXXXXMD01
:36B::PSTA//FAMT/50000000,
:19A::PSTA//EUR11111111,15
:16R:STAT
:25D::SETT//PENF
:16R:REAS
:24B::PENF//CLAC
:70D::REAS//SXAA015 - Failure of the settlement
DESCRIPTION 10
DESCRIPTION 11
DESCRIPTION 12
:16S:REAS
:16S:STAT
:16S:TRAN
:16S:RELTRAN
:16S:PENDET
:16R:PENDET
:20C::PCOM//211130067830614
:20C::PREF//N211130067830614
:22H::PNTP//SEFP
:22H::CALM//SECU
:17B::CMPU//N
:25D::PNST//ACTV
:19A::AMCO//EUR92,06
:99A::DAAC//001
:16R:CALDET
:98A::PEDA//20211130
:16R:FIA
:35B:ISIN XX00000000
:12A::CLAS/REGL/SOVR
:92A::GOMB//0,001
:16S:FIA
:19A::SECU//EUR11,06
:16S:CALDET
:16R:RELTRAN
:20C::ACOW//NONREF
:20C::MITI//2111262161219993
:16R:TRAN
:22H::REDE//RECE
:22H::PAYM//APMT
:22F::SETR//REPU
:22F::TRAN//SETT
:22F::BDEV/T2S/IDVP
:98A::SETT//20211129
:98C::ASTS//20211126181705
:98C::MTCH//20211126181705
:98C::SCTS//20211130143000
:97A::SAFE//XXXXXXXXXXXXD01000L10
:95P::ACOW//XXXXXXXXX01
:36B::PSTA//FAMT/7500000,
:19A::PSTA//EUR11111111,85
:16R:STAT
:25D::SETT//PENF
:16R:REAS
:24B::PENF//CLAC
:70D::REAS//SXAA015 - Failure of the settlement
DESCRIPTION 13
DESCRIPTION 14
DESCRIPTION 15
:16S:REAS
:16S:STAT
:16S:TRAN
:16S:RELTRAN
:16S:PENDET
:16S:PENACOUNT
:16S:PENACUR
:16S:PENA
-}{5:{CHK:0F4F93C68EA5}{TNG:}}_


My code:
MT537 mt537= MT537.parse(new String(fileContentMt537));
mt537.getSequenceBList();// conteins 5 sequece of STAT, but sequence B is only one.

![image](https://user-images.githubusercontent.com/95424570/145959028-f0fe3557-504b-4563-8651-b3372472bdd6.png)


Please is important, can you verify.

Regards

**Comment by zubri** [comment]
I see the issue. The heuristic asumes a sequence C exists, but that sequence C is not mandatory so it is not present in your sample.

**Comment by zubri** [comment]
The fixed code has been pushed. You can build a 9.2.9-SNAPSHOT with Gradle.

The official 9.2.9 version will be released in a few days along several other fixes and enhancements.

**Comment by zubri** [comment]
Version 9.2.9 has been release including this fix. The package will be available at Maven Central soon.

**Comment by AntonioFE2021** [comment]
thanks you so much
