### ISSUE TITLE
Message MT537 - Error reading Block B (STAT) 

### ISSUE THREAD

**Issue by AntonioFE2021** [prowide/prowide-core#82]
This is example messages:
MT537.txt:

_{1:F01XXXXXXXX0AXXX0400996471}{2:O5371305211201XXXXXXXXAXXX14523429742112011305N}{3:{108:xxxxxxxx}}{4:
:16R:GENL
:28E:5/LAST
:13A::STAT//513
:20C::SEME//000000000000251C
:23G:PENA
:98A::STAT//19700130
:22F::SFRE//DAIL
:22F::CODE//DELT
:22H::STST//PENA
:95P::ACOW//XXXXXXXX001
:97A::SAFE//NONREF
:17B::ACTI//Y
:16S:GENL
:16R:STAT
:25D::IPRC//CPRC
:16R:REAS
:24B::CAND//CANI
:70D::REAS//SXAA015 - Failure of the settlement
XXXXXXXX0XXXXXXXX0XXXXXXXX0
XXXXXXXX0XXXXXXXX0XXXXXXX0
XXXXXXXX0XXXXXXXX0XXXXXXXX0
terparty
:16S:REAS
:16S:STAT
:16R:PENA
:69A::STAT//19700101/19700130
:22F::CODE//CURR
:95P::ASDP//XXXXXXXXXXX
:16R:PENACUR
:11A::PECU//EUR
:98A::DACO//19700130
:95P::REPA//XXXXXXXX001
:95P::CASD//XXXXXXXX0XX
:95P::DCSD//XXXXXXXX0XX
:22F::TRCA//CSDP
:16R:PENACOUNT
:95P::REPA//XXXXXXXX0XX
:22F::TRCA//CCPA
:19A::AGNT//EUR1111,11
:16R:PENDET
:20C::PCOM//211130067774271
:20C::PREF//N211130067774271
:22H::PNTP//SEFP
:22H::CALM//SECU
:17B::CMPU//N
:25D::PNST//ACTV
:19A::AMCO//EUR111,
:99A::DAAC//001
:16R:CALDET
:98A::PEDA//19700130
:16R:FIA
:35B:ISIN XXXXXXXX0
:12A::CLAS/REGL/SOVR
:92A::GOMB//0,001
:16S:FIA
:19A::SECU//EUR1,
:16S:CALDET
:16R:RELTRAN
:20C::ACOW//NONREF
:20C::MITI//7001012161218562
:16R:TRAN
:22H::REDE//RECE
:22H::PAYM//APMT
:22F::SETR//REPU
:22F::TRAN//SETT
:22F::BDEV/T2S/IDVP
:98A::SETT//19700129
:98C::ASTS//19700126181652
:98C::MTCH//19700126181652
:98C::SCTS//19700130143000
:97A::SAFE//XXXXXXXXXX001000L10
:95P::ACOW//XXXXXXXX001
:36B::PSTA//FAMT/10000000,
:19A::PSTA//EUR111111,11
**:16R:STAT
:25D::SETT//PENF
:16R:REAS
:24B::PENF//CLAC
:70D::REAS//SXAA015 - example
example example example
example example example
example example example
terparty
:16S:REAS
:16S:STAT
:16S:TRAN
:16S:RELTRAN
:16S:PENDET
:16S:RELTRAN
:16S:PENDET
:16S:PENACOUNT
:16S:PENACUR
:16S:PENA
-}{5:{CHK:0F4F93C68EA5}{TNG:}}_

......
SequenceB is :
_:16R:STAT
:25D::IPRC//CPRC
:16R:REAS
:24B::CAND//CANI
:70D::REAS//SXAA015 - Failure of the settlement
XXXXXXXX0XXXXXXXX0XXXXXXXX0
XXXXXXXX0XXXXXXXX0XXXXXXX0
XXXXXXXX0XXXXXXXX0XXXXXXXX0
terparty
:16S:REAS
:16S:STAT_

My code is : 
MT537 mt537= MT537.parse(new String("MT537.txt"));
mt537.getSequence**B**List(); --> [0] sequenceBList() correct, [1] sequenceBlist() error, becouse contains sequence D1a1B1a. 
This sequence must contain only the first block STAT.

![image](https://user-images.githubusercontent.com/95424570/145054439-f9c5d862-a88a-4a48-abd5-da2a0ec0f94e.png)

Can you testing this message?

Regards

**Comment by zubri** [comment]
Duplicates #78
