### ISSUE TITLE
Parse message MT537  -  Block STAT

### ISSUE THREAD

**Issue by AntonioFE2021** [prowide/prowide-core#83]
**I reopen this issue trying to be more detailed.**

This is the original message with anonymous values:

_{1:F01XXXXXXX0AXXX0400996471}{2:O5371305211201XXXXXXX0AXXX14523429742112011305N}{3:{108:GCH-xxxxxxxxxxxx}}{4:
:16R:GENL
:28E:5/LAST
:13A::STAT//513
:20C::SEME//000000000000251C
:23G:PENA
:98A::STAT//20211130
:22F::SFRE//DAIL
:22F::CODE//DELT
:22H::STST//PENA
:95P::ACOW//XXXXXXXXX01
:97A::SAFE//NONREF
:17B::ACTI//Y
:16S:GENL
:16R:STAT
:25D::IPRC//CPRC
:16R:REAS
:24B::CAND//CANI
:70D::REAS//SXAA015 - Failure of the settlement
DESCRIPTION 111
DESCRIPTION 112
DESCRIPTION 113
terparty
:16S:REAS
:16S:STAT
:16R:PENA
:69A::STAT//20211101/20211130
:22F::CODE//CURR
:95P::ASDP//XXXXXXXXXXX
:16R:PENACUR
:11A::PECU//EUR
:98A::DACO//20211130
:95P::REPA//XXXXXXXXD01
:95P::CASD//XXXXXXXXXXX
:95P::DCSD//XXXXXXXXXXX
:22F::TRCA//CSDP
:16R:PENACOUNT
:95P::REPA//XXXXXXXXXXX
:22F::TRCA//CCPA
:19A::AGNT//EUR1,04
:16R:PENDET
:20C::PCOM//211130067774271
:20C::PREF//N211130067774271
:22H::PNTP//SEFP
:22H::CALM//SECU
:17B::CMPU//N
:25D::PNST//ACTV
:19A::AMCO//EUR1,
:99A::DAAC//001
:16R:CALDET
:98A::PEDA//20211130
:16R:FIA
:35B:ISIN XX0000000000
:12A::CLAS/REGL/SOVR
:92A::GOMB//0,001
:16S:FIA
:19A::SECU//EUR11,
:16S:CALDET
:16R:RELTRAN
:20C::ACOW//NONREF
:20C::MITI//2111262161218562
:16R:TRAN
:22H::REDE//RECE
:22H::PAYM//APMT
:22F::SETR//REPU
:22F::TRAN//SETT
:22F::BDEV/T2S/IDVP
:98A::SETT//20211129
:98C::ASTS//20211126181652
:98C::MTCH//20211126181652
:98C::SCTS//20211130143000
:97A::SAFE//XXXXXXXXXXXXXX1000XX0
:95P::ACOW//XXXXXXXXX01
:36B::PSTA//FAMT/50000000,
:19A::PSTA//EUR1111111,
:16R:STAT
:25D::SETT//PENF
:16R:REAS
:24B::PENF//CLAC
:70D::REAS//SXAA015 - Failure of the settlement
DESCRIPTION 101
DESCRIPTION 102
DESCRIPTION 103
:16S:REAS
:16S:STAT
:16S:TRAN
:16S:RELTRAN
:16S:PENDET
:16R:PENDET
:20C::PCOM//211130067807953
:20C::PREF//N211130067807953
:22H::PNTP//SEFP
:22H::CALM//SECU
:17B::CMPU//N
:25D::PNST//ACTV
:19A::AMCO//EUR111,5
:99A::DAAC//001
:16R:CALDET
:98A::PEDA//20211130
:16R:FIA
:35B:ISIN XX00000000
:12A::CLAS/REGL/SOVR
:92A::GOMB//0,001
:16S:FIA
:19A::SECU//EUR111,5
:16S:CALDET
:16R:RELTRAN
:20C::ACOW//NONREF
:20C::MITI//2111242159118671
:16R:TRAN
:22H::REDE//RECE
:22H::PAYM//APMT
:22F::SETR//TRAD
:22F::TRAN//SETT
:22F::BDEV/T2S/IDVP
:98A::SETT//20211125
:98C::ASTS//20211124181453
:98C::MTCH//20211124181453
:98C::SCTS//20211130143000
:97A::SAFE//XXXXXXXXXXXXXX1000X0
:95P::ACOW//XXXXXXXMD01
:36B::PSTA//FAMT/50000000,
:19A::PSTA//EUR111111111,75
:16R:STAT
:25D::SETT//PENF
:16R:REAS
:24B::PENF//CLAC
:70D::REAS//SXAA015 - Failure of the settlement
DESCRIPTION 1
DESCRIPTION 2
DESCRIPTION 3
:16S:REAS
:16S:STAT
:16S:TRAN
:16S:RELTRAN
:16S:PENDET
:16R:PENDET
:20C::PCOM//211130067821332
:20C::PREF//N211130067821332
:22H::PNTP//SEFP
:22H::CALM//SECU
:17B::CMPU//N
:25D::PNST//ACTV
:19A::AMCO//EUR111,
:99A::DAAC//001
:16R:CALDET
:98A::PEDA//20211130
:16R:FIA
:35B:ISIN XX00000000
:12A::CLAS/REGL/SOVR
:92A::GOMB//0,001
:16S:FIA
:19A::SECU//EUR111,
:16S:CALDET
:16R:RELTRAN
:20C::ACOW//NONREF
:20C::MITI//2111242159121848
:16R:TRAN
:22H::REDE//RECE
:22H::PAYM//APMT
:22F::SETR//TRAD
:22F::TRAN//SETT
:22F::BDEV/T2S/IDVP
:98A::SETT//20211125
:98C::ASTS//20211124181533
:98C::MTCH//20211124181533
:98C::SCTS//20211130143000
:97A::SAFE//XXXXXXXXXXD01000L10
:95P::ACOW//XXXXXXXMD01
:36B::PSTA//FAMT/50000000,
:19A::PSTA//EUR11111111,15
:16R:STAT
:25D::SETT//PENF
:16R:REAS
:24B::PENF//CLAC
:70D::REAS//SXAA015 - Failure of the settlement
DESCRIPTION 10
DESCRIPTION 11
DESCRIPTION 12
:16S:REAS
:16S:STAT
:16S:TRAN
:16S:RELTRAN
:16S:PENDET
:16R:PENDET
:20C::PCOM//211130067830614
:20C::PREF//N211130067830614
:22H::PNTP//SEFP
:22H::CALM//SECU
:17B::CMPU//N
:25D::PNST//ACTV
:19A::AMCO//EUR92,06
:99A::DAAC//001
:16R:CALDET
:98A::PEDA//20211130
:16R:FIA
:35B:ISIN XX00000000
:12A::CLAS/REGL/SOVR
:92A::GOMB//0,001
:16S:FIA
:19A::SECU//EUR11,06
:16S:CALDET
:16R:RELTRAN
:20C::ACOW//NONREF
:20C::MITI//2111262161219993
:16R:TRAN
:22H::REDE//RECE
:22H::PAYM//APMT
:22F::SETR//REPU
:22F::TRAN//SETT
:22F::BDEV/T2S/IDVP
:98A::SETT//20211129
:98C::ASTS//20211126181705
:98C::MTCH//20211126181705
:98C::SCTS//20211130143000
:97A::SAFE//XXXXXXXXXXXXD01000L10
:95P::ACOW//XXXXXXXXX01
:36B::PSTA//FAMT/7500000,
:19A::PSTA//EUR11111111,85
:16R:STAT
:25D::SETT//PENF
:16R:REAS
:24B::PENF//CLAC
:70D::REAS//SXAA015 - Failure of the settlement
DESCRIPTION 13
DESCRIPTION 14
DESCRIPTION 15
:16S:REAS
:16S:STAT
:16S:TRAN
:16S:RELTRAN
:16S:PENDET
:16S:PENACOUNT
:16S:PENACUR
:16S:PENA
-}{5:{CHK:0F4F93C68EA5}{TNG:}}_

When I try to extract sequenceB, STAT, using **mt537.getSequenceBList()**, I obtain also the sequences STAT  of Subsequence D1a1B1a,  this is not correct.

My code:
MT537 mt537= MT537.parse(new String(fileContentMt537));
mt537.getSequenceBList(); // contains 5 sequences of STAT, but sequence B is only one.

![image](https://user-images.githubusercontent.com/95424570/145959028-f0fe3557-504b-4563-8651-b3372472bdd6.png)

Instead, when I extract sequenceD1a1B1a using  **mt537.getSequenceD1a1B1aList()** I obtain correctly only 4 sequences  of the right block

![image](https://user-images.githubusercontent.com/95424570/145963609-bb40962f-f76c-413f-9042-babb68542146.png)

Please it's important, can you verify.

Regards

**Comment by zubri** [comment]
Fixed in #78
