### ISSUE TITLE
Message MT530 SequenceListC - ADDINFO

### ISSUE THREAD

**Issue by AntonioFE2021** [prowide/prowide-core#89]
Hello, 
I open this issue for a problem in the library SRU2021-9.2.9. In MT530 message the sequence C is a LIST, but in the library it's presented only as:

_public MT530.SequenceC getSequenceC()
     {
      return new MT530.SequenceC(super.getSwiftMessageNotNullOrException());
}_

Could you verify, please?

Thank you. Regards,

**Comment by zubri** [comment]
It has been fixed in the source code. The fix will be included in a release soon.

As a workaround you can get the sequences manually like this:

`mt.getSwiftMessage().getBlock4().getSubBlocks(SequenceC.START_END_16RS)`

**Comment by AntonioFE2021** [comment]
Thank's for new library 9.2.10 on Maven repository.

But I have found new bug in message MT530 on method toJson().
My code:
AbstractMT mt = AbstractMT.parse(new String(fileContent));
mt.toJson(); --> 
![image](https://user-images.githubusercontent.com/95424570/148734971-b945d996-4a99-4780-be2c-3964ee0305b2.png)


**This exception is present in all message MT that call method toJson**

Thank you. Regards,
