### ISSUE TITLE
Unable to parse MT messages using AbstractMT

### ISSUE THREAD

**Issue by jcjoof** [prowide/prowide-core#91]
I am getting the below warning while parsing MT messages:

Jan 06, 2022 10:21:48 AM com.prowidesoftware.swift.model.SwiftMessage toMT
WARNING: Cannot determine the message type from application header (block 2)

In response to this line of code: AbstractMT msg = AbstractMT.parse(Lib.readResource("C:\\swift\\emission1\\mt103.txt", null));

I am unable to get any field after this, becaue I keep getting NullException

**Comment by zubri** [comment]
Make sure your message is well-formed, having a proper block2.

If you have something like this in the file:

{1:F21AAAAUS33AXXX0221000001}{4:{177:1702040914}{451:0}}{1:F01AAAAUS33AXXX0221000001}{2:I103BBBBUS33XXXXN}

That's not a regular MT message but a service 21 message. Meaning it is an ACK followed by the actual MT message. 

If that's your case, you have to use the SwiftParser instead, to extract the actual FIN content that you intend to parse into an MT.

In order for the generic AbstractMT parse to work, your message should start with something like:

{1:F01AAAAUS33AXXX0221000001}{2:I103... etc

or 

{1:F01AAAAUS33AXXX0221000001}{2:O103... etc
