### ISSUE TITLE
Regression library 9.2.10 method toJson()

### ISSUE THREAD

**Issue by AntonioFE2021** [prowide/prowide-core#94]
Thank's for new library 9.2.10 on Maven repository.

But I have found one **regression**  in message MT530 on method toJson().
My code:
AbstractMT mt = AbstractMT.parse(new String(fileContent));
mt.toJson(); --> 
![image](https://user-images.githubusercontent.com/95424570/148734971-b945d996-4a99-4780-be2c-3964ee0305b2.png)

**This exception is present in all messages MT that call method toJson()**

Thank you. Regards,

**Comment by zubri** [comment]
We have updated the json dependency gson:2.8.8 -> gson:2.8.9
